name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v.4.2.2
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version-file: '.tool-versions'
      - name: "Build everything"
        run: "./gradlew build --no-daemon"
      - name: "Extract built .war file and remove Java stuff"
        run: "unzip web/build/libs/web.war && rm -r META-INF WEB-INF"
        working-directory: ./deployment
      - name: "Upload static files as artifact"
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v.3.0.1
        with:
          path: ./deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: "Deploy to GH pages"
        id: deployment
        using: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v.4.0.5
          
